### ISSUE TITLE
Win?

### ISSUE THREAD

**Issue by gannotsk21** [Katacka/Dominion#32]
Can you add, something that says who's winning.  I don't remember any of the cards I've pressed...maybe I'm under standing the game incorrectly.

**Comment by liao21** [comment]
Part of the *board* game is that you don't know how many victory points any other player has at a given time. In the online version, it is displayed, we decided to stay true to the board version because a user could technically count cards to find out how the other players were doing. 

As for not remembering which cards you played, we are aware of this bug and we'll be working on a buffer feature in the GUI where your cards will go after you play them and before you end your turn. At the end of the turn, they will all still go to the discard. 

This will change Smart AI functionality because it exploits this bug in the gamestate. Good catch.

**Comment by Katacka** [comment]
Smart AI has been fixed, however in-play cards are still in development. Hayden and Ashika have been working on this task

**Comment by regier21** [comment]
Issue resolved.
